# -*- coding: utf-8 -*-
"""superstore project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nerVrfM5j-ENz7oENe5gRMnUg8j_llhj
"""

import pandas as pd
df=pd.read_csv("/content/Sample - Superstore.csv", encoding='latin1')
df

#first 5 rows
df.head()

#display columns
df.columns

#last 5 rows
df.tail()

#display count of rows and columns
df.shape

#informatiom
df.info()

#check null values
df.isnull().sum()

#check duplicate values(repetated values)
df.duplicated().sum()

#count  of sales by category
x=df.groupby('Category')['Sales'].count()
x

#sum  of sales by category
x=df.groupby('Category')['Sales'].sum()
x

#state wise sales
import matplotlib.pyplot as plt
top_states = df.groupby('State')['Sales'].sum()

top_states.plot(kind='bar')

plt.title("State Wise Sales")
plt.xlabel("State")
plt.ylabel("Sales")

plt.show()

#region was profit
region_profit = df.groupby('Region')['Profit'].sum()
print(region_profit)

#shipping mode
df['Ship Mode'].value_counts().plot(kind='bar')
plt.title("Ship Mode Count")
plt.xlabel("Ship Mode")
plt.ylabel("Number of Orders")
plt.show()

sub_profit = df.groupby('Sub-Category')['Profit'].sum()

print(sub_profit)

